### ISSUE TITLE
The fftw-based example does not appear to work with binder

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xwebrtc#8]
cc @martinRenou

**Comment by martinRenou** [comment]
It looks like `recorder.save()` saves an empty image in `record.png`, I'll try locally

**Comment by martinRenou** [comment]
The problem is with `ximage` from `xwidgets`, the value of the image is empty after saving a record from the video stream (I guess not synchronized from the frontend to the backend). I could reproduce the bug with `xwebrtc:    0.2.0` and `xwidgets:   0.14.0` and later, but using `xwebrtc:    0.1.1` and `xwidgets:   0.13.1` it works.
From `xwebrtc:    0.1.1` to `xwebrtc:    0.2.0` there was no change in the code, only a dependency change for `xwidgets`. So I suspect `xwidgets:   0.13.1 -> 0.14.0` is the cause of this bug.
